apiVersion: v1
kind: Service
metadata:
  namespace: demo-ns
  name: redis-service
  labels:
    app: redis
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: redis
  type: NodePort