apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: demo-ns
type: Opaque # a generic secret that can store in type of data
# used for plain data. if we used "data" then it had to be base64 encoded
stringData:
  API_NINJA_API_KEY: "mwS/NxfCRHN9GVNGz2otbA==l9IWM5ThYclb07WC"
---
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJzaW5hazIwMDIiLCJwYXNzd29yZCI6IjEyMTE1NHNpbmEiLCJlbWFpbCI6ImtzaW5hODI3OUBnbWFpbC5jb20iLCJhdXRoIjoiYzJsdVlXc3lNREF5T2pFeU1URTFOSE5wYm1FPSJ9fX0=
kind: Secret
metadata:
  name: regcred
  namespace: demo-ns
type: kubernetes.io/dockerconfigjson