apiVersion: v1
kind: Service
metadata:
  namespace: demo-ns
  name: dictionary-service
  labels:
    app: spring-backend
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: spring-backend
  type: LoadBalancer
