name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build poject
      run: ./mvnw clean package -Dskiptests
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag sinak2002/dictionary:$(date +%s)
